language: php

sudo: required

before_install:
  - curl https://wikitech.wikimedia.org/w/index.php?title=APT_repository/Key&action=raw | sudo apt-key add -
  - echo "deb http://apt.wikimedia.org/wikimedia trusty-wikimedia main experimental backports" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get -qq update
  - sudo apt-get install -y arcanist

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  include:
    - php: 5.6
  fast_finish: true

install:
  - export COMPOSER_ROOT_VERSION=dev-master
  - if [ "$DEPENDENCIES" == "dev" ]; then perl -pi -e 's/^}$/,"minimum-stability":"dev"}/' composer.json; fi;
  - if [ "$DEPENDENCIES" != "low" ]; then composer update; fi;
  - if [ "$DEPENDENCIES" == "low" ]; then composer update --prefer-lowest; fi;

script:
   - vendor/bin/phpspec run --format=pretty
